// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectApp.Models;

namespace ProjectApp.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20191026090506_Initial3")]
    partial class Initial3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectApp.Models.AvatarUser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("image");

                    b.Property<int>("user_id");

                    b.HasKey("id");

                    b.HasIndex("user_id")
                        .IsUnique();

                    b.ToTable("AvatarUser");
                });

            modelBuilder.Entity("ProjectApp.Models.BannedUser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("expires_ban");

                    b.Property<string>("reason_ban")
                        .IsRequired();

                    b.Property<int>("user_id");

                    b.HasKey("id");

                    b.HasIndex("user_id")
                        .IsUnique();

                    b.ToTable("BannedUsers");
                });

            modelBuilder.Entity("ProjectApp.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBithday");

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<string>("first_name");

                    b.Property<bool>("isAdmin");

                    b.Property<string>("last_name");

                    b.Property<string>("password")
                        .IsRequired();

                    b.Property<string>("phone");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjectApp.Models.AvatarUser", b =>
                {
                    b.HasOne("ProjectApp.Models.User", "User")
                        .WithOne("avatar")
                        .HasForeignKey("ProjectApp.Models.AvatarUser", "user_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProjectApp.Models.BannedUser", b =>
                {
                    b.HasOne("ProjectApp.Models.User", "User")
                        .WithOne("bannedUser")
                        .HasForeignKey("ProjectApp.Models.BannedUser", "user_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
